// Who this build of the engine is: the names, folders and release stream it
// identifies itself by.
//
// MD Boss never sets this, and every default below is exactly the value that
// used to be a literal in the unit that uses it -- so for MD Boss nothing
// changes.  It exists because DocBoss compiles these same translation units
// straight out of this tree (see DocBoss/CLAUDE.md), and without it a pulled
// unit would read and write MD Boss's own profile, register as MD Boss's
// ProgId, share its single-instance mutex and update itself from MD Boss's
// releases.  None of those fail loudly; each one quietly corrupts the other
// app.
//
// Set once, at the very start of OnInit, before anything reads it.  Nothing
// here is consulted from a static initialiser, so there is no order problem.

#ifndef MDBOSS_APP_APP_IDENTITY_H
#define MDBOSS_APP_APP_IDENTITY_H

#include <string>

namespace mdboss {

struct AppIdentity {
    // Shown in generated text ("Generated by MD Boss") and message boxes.
    std::string display_name = "MD Boss";
    // The per-user data folder (config.json, templates, favorites).  Empty
    // means %APPDATA%\MDBoss, falling back to %USERPROFILE%\MDBoss.
    std::string data_dir;
    // Where the preview stages its page and keeps its WebView2 profile.
    // Empty means %TEMP%\MDBoss.
    std::string staging_dir;

    // File association (FileAssoc.cpp).
    std::string prog_id = "MDBoss.Markdown";
    std::string assoc_display_name = "MD Boss";
    // Also names the Software\<assoc_app_name>\Capabilities key.
    std::string assoc_app_name = "MDBoss";
    std::string assoc_description =
        "Local Markdown manager, editor, and offline GitHub-style viewer.";

    // Single instance (SingleInstance.cpp).
    std::wstring instance_prop = L"MDBossCpp.Instance";
    std::wstring instance_mutex = L"Local\\MDBossCpp.SingleInstance";

    // Release stream (Updater.cpp, UpdaterHttp.cpp).
    std::string releases_api_url =
        "https://api.github.com/repos/Flinterpop/MDBoss/releases/latest";
    std::string releases_page_url = "https://github.com/Flinterpop/MDBoss/releases";
    std::string setup_asset = "MDBoss-Cpp-Setup.exe";
    std::string portable_asset = "MDBoss-Cpp-Portable.zip";
    // The exe the portable zip must contain, at its root or one folder down
    // (<portable_folder>\<exe_name>).
    std::string exe_name = "MDBoss.exe";
    std::string portable_folder = "MDBoss";
};

// The identity in effect.  MD Boss's defaults until set_app_identity().
const AppIdentity& app_identity();

// Replace the identity.  Call once, before any window exists.
void set_app_identity(const AppIdentity& identity);

// The per-user data folder, resolved: AppIdentity::data_dir if set, else
// %APPDATA%\MDBoss (or %USERPROFILE%\MDBoss).  UTF-8.
std::string user_data_dir();

}  // namespace mdboss

#endif  // MDBOSS_APP_APP_IDENTITY_H
