// Parity tests: the C++ renderer against the Python renderer's output.
//
// The corpus in golden/ is generated by make_golden.py from the repo-root
// mdrender.py, which is the reference implementation.  A failure here means
// this port diverged, not that the expectation is stale -- regenerate the
// corpus only when mdrender.py itself is deliberately changed.

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <catch2/catch_test_macros.hpp>

#include "mdrender/MdRender.h"

namespace {

struct Case {
    std::string name;
    bool strip_yaml = false;
};

std::filesystem::path golden_dir()
{
    return std::filesystem::path{MDBOSS_GOLDEN_DIR};
}

std::string read_file(const std::filesystem::path& path)
{
    std::ifstream stream(path, std::ios::binary);
    REQUIRE(stream.good());
    std::ostringstream buffer;
    buffer << stream.rdbuf();
    return buffer.str();
}

// Golden files are written with LF; normalise in case git ever checks them
// out with CRLF on this Windows tree.
std::string normalise(std::string text)
{
    text.erase(std::remove(text.begin(), text.end(), '\r'), text.end());
    return text;
}

std::vector<Case> load_index()
{
    const std::string text = normalise(read_file(golden_dir() / "index.tsv"));
    std::vector<Case> cases;
    std::istringstream stream(text);
    std::string line;
    while (std::getline(stream, line)) {
        const std::size_t tab = line.find('\t');
        if (tab == std::string::npos) {
            continue;
        }
        cases.push_back(Case{line.substr(0, tab), line.substr(tab + 1) == "1"});
    }
    return cases;
}

// Pygments highlights server-side in Python; this port emits the plain
// <pre><code class="language-x"> form that mdrender.py itself falls back to
// when no lexer matches.  Until that divergence is settled (see the plan's
// "One deliberate divergence to settle"), highlighted blocks are compared as
// opaque units so the surrounding document is still checked strictly.
constexpr std::string_view kCodeMarker = "\x01HIGHLIGHTED-CODE\x01";

std::string mask_region(std::string text, std::string_view open,
                        std::string_view close)
{
    std::string out;
    std::size_t pos = 0;
    while (pos <= text.size()) {
        const std::size_t start = text.find(open, pos);
        if (start == std::string::npos) {
            out.append(text, pos, std::string::npos);
            break;
        }
        const std::size_t end = text.find(close, start);
        if (end == std::string::npos) {
            out.append(text, pos, std::string::npos);
            break;
        }
        out.append(text, pos, start - pos);
        out.append(kCodeMarker);
        pos = end + close.size();
    }
    return out;
}

bool has_highlight(const std::string& expected)
{
    return expected.find("<div class=\"highlight\">") != std::string::npos;
}

std::string mask_expected(std::string text)
{
    return mask_region(std::move(text), "<div class=\"highlight\">",
                       "</pre></div>\n");
}

std::string mask_actual(std::string text)
{
    return mask_region(std::move(text), "<pre><code class=\"language-",
                       "</code></pre>\n");
}

// On a mismatch, dump what was produced next to the golden file and describe
// the first differing line.  Whole-document diffs are unreadable inline, and
// the corpus includes README.md and HELP.md, which are hundreds of lines.
std::string describe_mismatch(const std::string& name,
                              const std::string& suffix,
                              const std::string& expected,
                              const std::string& actual)
{
    const std::filesystem::path dump =
        golden_dir() / (name + ".actual" + suffix);
    std::ofstream out(dump, std::ios::binary);
    if (out) {
        out << actual;
    }

    std::istringstream want(expected);
    std::istringstream got(actual);
    std::string want_line;
    std::string got_line;
    int number = 0;
    while (true) {
        const bool have_want = static_cast<bool>(std::getline(want, want_line));
        const bool have_got = static_cast<bool>(std::getline(got, got_line));
        if (!have_want && !have_got) {
            break;
        }
        ++number;
        if (want_line != got_line) {
            return "first difference at line " + std::to_string(number) +
                   "\n  expected: " + (have_want ? want_line : "<eof>") +
                   "\n  actual:   " + (have_got ? got_line : "<eof>") +
                   "\n  dumped:   " + dump.string();
        }
    }
    return "documents differ only in trailing bytes; dumped: " + dump.string();
}

std::string serialise_outline(const std::vector<mdrender::Heading>& outline)
{
    std::string text;
    for (const mdrender::Heading& heading : outline) {
        text += std::to_string(heading.level);
        text += '\t';
        text += heading.text;
        text += '\t';
        text += heading.slug;
        text += '\n';
    }
    return text;
}

}  // namespace

TEST_CASE("golden corpus is present", "[golden]")
{
    REQUIRE(std::filesystem::is_directory(golden_dir()));
    const std::vector<Case> cases = load_index();
    REQUIRE(cases.size() >= 20);
}

TEST_CASE("rendered body matches the Python renderer", "[golden][body]")
{
    for (const Case& item : load_index()) {
        const std::string source =
            normalise(read_file(golden_dir() / (item.name + ".md")));
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".html")));
        const std::string actual =
            normalise(mdrender::render_body(source, item.strip_yaml));

        const std::string want =
            has_highlight(expected) ? mask_expected(expected) : expected;
        const std::string got =
            has_highlight(expected) ? mask_actual(actual) : actual;

        INFO("case: " << item.name);
        if (want != got) {
            FAIL_CHECK(describe_mismatch(item.name, ".html", want, got));
        }
    }
}

TEST_CASE("outline matches the Python renderer", "[golden][outline]")
{
    for (const Case& item : load_index()) {
        const std::string source =
            normalise(read_file(golden_dir() / (item.name + ".md")));
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".outline")));
        const std::string actual = serialise_outline(
            mdrender::extract_outline(source, item.strip_yaml));

        INFO("case: " << item.name);
        if (actual != expected) {
            FAIL_CHECK(
                describe_mismatch(item.name, ".outline", expected, actual));
        }
    }
}

// The parity check above masks Pygments-highlighted code blocks.  Masking
// anything silently would let the corpus read as "fully matching" when part of
// it is not compared at all, so name the cases out loud.
TEST_CASE("known divergences are reported, not hidden", "[golden][divergence]")
{
    std::vector<std::string> masked;
    for (const Case& item : load_index()) {
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".html")));
        if (has_highlight(expected)) {
            masked.push_back(item.name);
        }
    }

    std::string report =
        "Pygments highlighting is not ported; code blocks compared as opaque "
        "units in " +
        std::to_string(masked.size()) + " case(s):";
    for (const std::string& name : masked) {
        report += "\n  - " + name;
    }
    WARN(report);

    // Everything outside those blocks is still compared strictly, so the
    // masking must stay narrow.  If most of the corpus ends up masked, the
    // parity signal is gone and this needs revisiting.
    CHECK(masked.size() * 2 < load_index().size());
}

TEST_CASE("render_document fills every placeholder", "[document]")
{
    REQUIRE(mdrender::set_asset_dir(MDBOSS_ASSET_DIR));
    const std::string page = mdrender::render_document(
        "# Title\n\ntext\n", "file:///c:/docs/", "Doc", false);

    REQUIRE_FALSE(page.empty());
    CHECK(page.find("@@MDBOSS") == std::string::npos);
    CHECK(page.find("href=\"file:///c:/docs/\"") != std::string::npos);
    CHECK(page.find("mermaid.min.js") != std::string::npos);
    CHECK(page.find("katex.min.css") != std::string::npos);
    CHECK(page.find("<title>Doc</title>") != std::string::npos);
    CHECK(page.find("id=\"title\"") != std::string::npos);
}

TEST_CASE("front matter is only stripped when asked", "[frontmatter]")
{
    const std::string doc = "---\ntitle: x\n---\n\n# H\n";
    CHECK(mdrender::render_body(doc, false).find("title: x") !=
          std::string::npos);
    CHECK(mdrender::render_body(doc, true).find("title: x") ==
          std::string::npos);
    // A horizontal rule further down must survive.
    CHECK(mdrender::render_body("# A\n\ntext\n\n---\n\nmore\n", true)
              .find("<hr />") != std::string::npos);
}
