// Parity tests: the C++ renderer against the Python renderer's output.
//
// The corpus in golden/ is generated by make_golden.py from the repo-root
// mdrender.py, which is the reference implementation.  A failure here means
// this port diverged, not that the expectation is stale -- regenerate the
// corpus only when mdrender.py itself is deliberately changed.

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <catch2/catch_test_macros.hpp>

#include "mdrender/MdRender.h"

namespace {

struct Case {
    std::string name;
    bool strip_yaml = false;
};

std::filesystem::path golden_dir()
{
    return std::filesystem::path{MDBOSS_GOLDEN_DIR};
}

std::string read_file(const std::filesystem::path& path)
{
    std::ifstream stream(path, std::ios::binary);
    REQUIRE(stream.good());
    std::ostringstream buffer;
    buffer << stream.rdbuf();
    return buffer.str();
}

// Golden files are written with LF; normalise in case git ever checks them
// out with CRLF on this Windows tree.
std::string normalise(std::string text)
{
    text.erase(std::remove(text.begin(), text.end(), '\r'), text.end());
    return text;
}

std::vector<Case> load_index()
{
    const std::string text = normalise(read_file(golden_dir() / "index.tsv"));
    std::vector<Case> cases;
    std::istringstream stream(text);
    std::string line;
    while (std::getline(stream, line)) {
        const std::size_t tab = line.find('\t');
        if (tab == std::string::npos) {
            continue;
        }
        cases.push_back(Case{line.substr(0, tab), line.substr(tab + 1) == "1"});
    }
    return cases;
}

// Pygments highlights server-side in Python; this port emits the plain
// <pre><code class="language-x"> form that mdrender.py itself falls back to
// when no lexer matches.  Until that divergence is settled (see the plan's
// "One deliberate divergence to settle"), highlighted blocks are compared as
// opaque units so the surrounding document is still checked strictly.
constexpr std::string_view kCodeMarker = "\x01HIGHLIGHTED-CODE\x01";

std::string mask_region(std::string text, std::string_view open,
                        std::string_view close)
{
    std::string out;
    std::size_t pos = 0;
    while (pos <= text.size()) {
        const std::size_t start = text.find(open, pos);
        if (start == std::string::npos) {
            out.append(text, pos, std::string::npos);
            break;
        }
        const std::size_t end = text.find(close, start);
        if (end == std::string::npos) {
            out.append(text, pos, std::string::npos);
            break;
        }
        out.append(text, pos, start - pos);
        out.append(kCodeMarker);
        pos = end + close.size();
    }
    return out;
}

bool has_highlight(const std::string& expected)
{
    return expected.find("<div class=\"highlight\">") != std::string::npos;
}

std::string mask_expected(std::string text)
{
    return mask_region(std::move(text), "<div class=\"highlight\">",
                       "</pre></div>\n");
}

std::string mask_actual(std::string text)
{
    return mask_region(std::move(text), "<pre><code class=\"language-",
                       "</code></pre>\n");
}

// On a mismatch, dump what was produced next to the golden file and describe
// the first differing line.  Whole-document diffs are unreadable inline, and
// the corpus includes README.md and HELP.md, which are hundreds of lines.
std::string describe_mismatch(const std::string& name,
                              const std::string& suffix,
                              const std::string& expected,
                              const std::string& actual)
{
    const std::filesystem::path dump =
        golden_dir() / (name + ".actual" + suffix);
    std::ofstream out(dump, std::ios::binary);
    if (out) {
        out << actual;
    }

    std::istringstream want(expected);
    std::istringstream got(actual);
    std::string want_line;
    std::string got_line;
    int number = 0;
    while (true) {
        const bool have_want = static_cast<bool>(std::getline(want, want_line));
        const bool have_got = static_cast<bool>(std::getline(got, got_line));
        if (!have_want && !have_got) {
            break;
        }
        ++number;
        if (want_line != got_line) {
            return "first difference at line " + std::to_string(number) +
                   "\n  expected: " + (have_want ? want_line : "<eof>") +
                   "\n  actual:   " + (have_got ? got_line : "<eof>") +
                   "\n  dumped:   " + dump.string();
        }
    }
    return "documents differ only in trailing bytes; dumped: " + dump.string();
}

std::string serialise_outline(const std::vector<mdrender::Heading>& outline)
{
    std::string text;
    for (const mdrender::Heading& heading : outline) {
        text += std::to_string(heading.level);
        text += '\t';
        text += heading.text;
        text += '\t';
        text += heading.slug;
        text += '\n';
    }
    return text;
}

}  // namespace

TEST_CASE("golden corpus is present", "[golden]")
{
    REQUIRE(std::filesystem::is_directory(golden_dir()));
    const std::vector<Case> cases = load_index();
    REQUIRE(cases.size() >= 20);
}

TEST_CASE("rendered body matches the Python renderer", "[golden][body]")
{
    for (const Case& item : load_index()) {
        const std::string source =
            normalise(read_file(golden_dir() / (item.name + ".md")));
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".html")));
        const std::string actual =
            normalise(mdrender::render_body(source, item.strip_yaml));

        const std::string want =
            has_highlight(expected) ? mask_expected(expected) : expected;
        const std::string got =
            has_highlight(expected) ? mask_actual(actual) : actual;

        INFO("case: " << item.name);
        if (want != got) {
            FAIL_CHECK(describe_mismatch(item.name, ".html", want, got));
        }
    }
}

TEST_CASE("outline matches the Python renderer", "[golden][outline]")
{
    for (const Case& item : load_index()) {
        const std::string source =
            normalise(read_file(golden_dir() / (item.name + ".md")));
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".outline")));
        const std::string actual = serialise_outline(
            mdrender::extract_outline(source, item.strip_yaml));

        INFO("case: " << item.name);
        if (actual != expected) {
            FAIL_CHECK(
                describe_mismatch(item.name, ".outline", expected, actual));
        }
    }
}

// The parity check above masks Pygments-highlighted code blocks.  Masking
// anything silently would let the corpus read as "fully matching" when part of
// it is not compared at all, so name the cases out loud.
TEST_CASE("known divergences are reported, not hidden", "[golden][divergence]")
{
    std::vector<std::string> masked;
    for (const Case& item : load_index()) {
        const std::string expected =
            normalise(read_file(golden_dir() / (item.name + ".html")));
        if (has_highlight(expected)) {
            masked.push_back(item.name);
        }
    }

    std::string report =
        "Pygments highlighting is not ported; code blocks compared as opaque "
        "units in " +
        std::to_string(masked.size()) + " case(s):";
    for (const std::string& name : masked) {
        report += "\n  - " + name;
    }
    WARN(report);

    // Everything outside those blocks is still compared strictly, so the
    // masking must stay narrow.  If most of the corpus ends up masked, the
    // parity signal is gone and this needs revisiting.
    CHECK(masked.size() * 2 < load_index().size());
}

TEST_CASE("render_document fills every placeholder", "[document]")
{
    REQUIRE(mdrender::set_asset_dir(MDBOSS_ASSET_DIR));
    const std::string page = mdrender::render_document(
        "# Title\n\ntext\n", "file:///c:/docs/", "Doc", false);

    REQUIRE_FALSE(page.empty());
    CHECK(page.find("@@MDBOSS") == std::string::npos);
    CHECK(page.find("href=\"file:///c:/docs/\"") != std::string::npos);
    CHECK(page.find("mermaid.min.js") != std::string::npos);
    CHECK(page.find("katex.min.css") != std::string::npos);
    CHECK(page.find("<title>Doc</title>") != std::string::npos);
    CHECK(page.find("id=\"title\"") != std::string::npos);
    // This port highlights client-side, so the page must carry highlight.js
    // and must not reference the Python renderer's Pygments stylesheet.
    CHECK(page.find("highlight.min.js") != std::string::npos);
    CHECK(page.find("pygments-github.css") == std::string::npos);
    // The scroll bridge must be the WebView2 one.  The check is for a loaded
    // qrc: script rather than the bare word: the template's header comment
    // explains why Qt's channel cannot be used here, and that prose is
    // documentation, not a dependency.
    CHECK(page.find("chrome.webview") != std::string::npos);
    CHECK(page.find("src=\"qrc:") == std::string::npos);
}

// The bundled render assets must all exist and stay local: the preview is
// network-locked, so anything the template references by URL has to be on
// disk or it simply will not load.
TEST_CASE("bundled assets referenced by the template exist", "[assets]")
{
    REQUIRE(mdrender::set_asset_dir(MDBOSS_ASSET_DIR));
    const std::filesystem::path root{MDBOSS_ASSET_DIR};
    const char* const required[] = {
        "template-webview2.html",
        "github-markdown-light.css",
        "mermaid.min.js",
        "katex/katex.min.css",
        "katex/katex.min.js",
        "highlight/highlight.min.js",
        "highlight/github.min.css",
    };
    for (const char* name : required) {
        INFO("missing bundled asset: " << name);
        CHECK(std::filesystem::exists(root / name));
    }
}

TEST_CASE("front matter is only stripped when asked", "[frontmatter]")
{
    const std::string doc = "---\ntitle: x\n---\n\n# H\n";
    CHECK(mdrender::render_body(doc, false).find("title: x") !=
          std::string::npos);
    CHECK(mdrender::render_body(doc, true).find("title: x") ==
          std::string::npos);
    // A horizontal rule further down must survive.
    CHECK(mdrender::render_body("# A\n\ntext\n\n---\n\nmore\n", true)
              .find("<hr />") != std::string::npos);
}

// ---- document_title ------------------------------------------------------
//
// This is what the Save dialog offers as a filename for a document that has
// never been saved, so a wrong answer puts a wrong name in front of the user
// at the one moment they are least likely to read it carefully.

TEST_CASE("a theme changes only the dressing, never the body", "[theme]")
{
    // The claim the whole design rests on, and the reason ~30 golden files
    // cannot be disturbed by adding a theme: render_body() has no theme
    // parameter at all, so the generated HTML is identical and only the two
    // stylesheet links and the <body> class differ.
    REQUIRE(mdrender::set_asset_dir(MDBOSS_ASSET_DIR));
    const std::string md = "# Title\n\ntext with `code` and a [link](x).\n";

    const std::string github = mdrender::render_document(
        md, "file:///c:/x/", "T", false, mdrender::Theme::kGitHub);
    const std::string notes = mdrender::render_document(
        md, "file:///c:/x/", "T", false, mdrender::Theme::kNotes);

    const std::string body = mdrender::render_body(md, false);
    REQUIRE_FALSE(body.empty());
    CHECK(github.find(body) != std::string::npos);
    CHECK(notes.find(body) != std::string::npos);

    // The dressing, and only the dressing.
    //
    // Matched WITH the closing quote, so this tests the href of a <link> and
    // not merely the name appearing somewhere: the template's inline style
    // carries a comment naming github-markdown-light.css, which a bare
    // substring search finds in the Notes page too and fails on.
    const auto links = [](const std::string& page, const char* file) {
        return page.find(std::string(file) + "\"") != std::string::npos;
    };
    CHECK(links(github, "github-markdown-light.css"));
    CHECK_FALSE(links(github, "notes-light.css"));
    CHECK(links(notes, "notes-light.css"));
    CHECK_FALSE(links(notes, "github-markdown-light.css"));

    CHECK(links(github, "highlight/github.min.css"));
    CHECK(links(notes, "highlight/xcode.min.css"));

    // The body class is what lets the theme sheet outrank the template's own
    // inline <style>; without it the layout rules silently lose.
    CHECK(notes.find("theme-notes") != std::string::npos);
    CHECK(github.find("theme-github") != std::string::npos);

    // No placeholder may survive in either.
    CHECK(github.find("@@MDBOSS_") == std::string::npos);
    CHECK(notes.find("@@MDBOSS_") == std::string::npos);
}

TEST_CASE("theme names round-trip and fall back", "[theme]")
{
    CHECK(mdrender::theme_name(mdrender::Theme::kGitHub) == "github");
    CHECK(mdrender::theme_name(mdrender::Theme::kNotes) == "notes");
    CHECK(mdrender::theme_from_name("notes") == mdrender::Theme::kNotes);
    CHECK(mdrender::theme_from_name("github") == mdrender::Theme::kGitHub);
    // A profile written by a later build, or a hand-edited one, must render
    // as something rather than fail.
    CHECK(mdrender::theme_from_name("") == mdrender::Theme::kGitHub);
    CHECK(mdrender::theme_from_name("solarized") == mdrender::Theme::kGitHub);
}

TEST_CASE("every theme's stylesheets are actually bundled", "[theme][assets]")
{
    // The same guard the GitHub assets already have: a theme whose CSS is not
    // shipped renders as unstyled text, and only in the installed build.
    REQUIRE(mdrender::set_asset_dir(MDBOSS_ASSET_DIR));
    const std::filesystem::path assets(MDBOSS_ASSET_DIR);
    for (const char* name : {"github-markdown-light.css", "notes-light.css",
                             "highlight/github.min.css",
                             "highlight/xcode.min.css"}) {
        INFO(name);
        CHECK(std::filesystem::is_regular_file(assets / name));
    }
}

TEST_CASE("a task list renders as checkboxes", "[mdrender][tasklist]")
{
    // Found by looking at the preview, not by a test: ToDoList.md is written
    // as a checklist and rendered as bullets with a literal "[ ]" in them,
    // because MD_FLAG_TASKLISTS was off and the <li> handler ignored is_task.
    // Not specific to that file -- any document using GitHub's task-list
    // syntax was rendering wrong.
    const std::string html =
        mdrender::render_body("- [ ] open\n- [x] done\n", false);

    CHECK(html.find("[ ]") == std::string::npos);
    CHECK(html.find("[x]") == std::string::npos);
    CHECK(html.find("type=\"checkbox\"") != std::string::npos);

    // Disabled, as GitHub renders them: the preview is a view of the file, so
    // a box that could be ticked without the file changing would be lying.
    CHECK(html.find("disabled") != std::string::npos);

    // The ticked one, and only the ticked one, carries checked.
    const std::size_t checked = html.find("checked");
    REQUIRE(checked != std::string::npos);
    CHECK(html.find("checked", checked + 1) == std::string::npos);
    CHECK(checked > html.find("open"));   // the second item is the ticked one
}

TEST_CASE("an ordinary list is untouched by the task-list flag",
          "[mdrender][tasklist]")
{
    // The flag applies to every document, so the far commoner case -- a plain
    // bullet list -- must render exactly as before.
    const std::string html = mdrender::render_body("- one\n- two\n", false);
    CHECK(html.find("checkbox") == std::string::npos);
    CHECK(html.find("<li>") != std::string::npos);
}

TEST_CASE("a bare URL in a table cell becomes a link", "[mdrender][autolink]")
{
    // logins.md keeps its Link column as bare URLs -- a table cell is a poor
    // place to type [text](url) by hand -- and a URL you cannot click is not a
    // link, it is a string to retype.
    const std::string html = mdrender::render_body(
        "| Name | Link |\n|---|---|\n"
        "| Example | https://example.com/login |\n",
        false);
    CHECK(html.find("<a href=\"https://example.com/login\"") !=
          std::string::npos);
}

TEST_CASE("bare URLs, www and email autolink in prose too",
          "[mdrender][autolink]")
{
    // The flag applies to every document, which is the point: any document
    // listing a URL was rendering it as plain text.
    CHECK(mdrender::render_body("See http://example.com now\n", false)
              .find("<a href=\"http://example.com\"") != std::string::npos);
    CHECK(mdrender::render_body("See www.example.com now\n", false)
              .find("href=\"http://www.example.com\"") != std::string::npos);
    CHECK(mdrender::render_body("Mail a@example.com now\n", false)
              .find("href=\"mailto:a@example.com\"") != std::string::npos);

    // An explicit link is untouched -- the far commoner case must not change.
    const std::string explicit_link =
        mdrender::render_body("[text](https://example.com)\n", false);
    CHECK(explicit_link.find("<a href=\"https://example.com\">text</a>") !=
          std::string::npos);
}

TEST_CASE("autolinking cannot mint a dangerous scheme", "[mdrender][autolink]")
{
    // The reason this flag is safe to turn on: the permissive rules match only
    // http/https/ftp and mailto shapes, so no javascript: or file: URL can be
    // created from prose.  PreviewPane allow-lists the scheme again before
    // handing anything to ShellExecute, but defence in depth starts here.
    for (const char* const text : {"javascript:alert(1)\n",
                                   "file:///C:/Windows/System32/cmd.exe\n",
                                   "data:text/html,<script>\n",
                                   "vbscript:msgbox\n"}) {
        const std::string html = mdrender::render_body(text, false);
        INFO(text);
        CHECK(html.find("<a href") == std::string::npos);
    }

    // A code span is still literal: autolinking inside one would rewrite text
    // whose whole purpose is to be shown exactly as written.
    CHECK(mdrender::render_body("`http://example.com`\n", false)
              .find("<a href") == std::string::npos);
}

TEST_CASE("the first heading is the title", "[mdrender][title]")
{
    CHECK(mdrender::document_title("# The Rule\n\nbody\n") == "The Rule");
    // Any level, not just h1: a document may well start at ##.
    CHECK(mdrender::document_title("## Deeper\n\nbody\n") == "Deeper");
    // The FIRST heading, not the largest one later.
    CHECK(mdrender::document_title("## First\n\n# Second\n") == "First");
    CHECK(mdrender::document_title("") == "");
    CHECK(mdrender::document_title("no headings here\n") == "");
}

TEST_CASE("front matter title wins over the heading", "[mdrender][title]")
{
    CHECK(mdrender::document_title("---\ntitle: From Meta\n---\n\n# From "
                                   "Heading\n") == "From Meta");
    // Quoted scalars are unwrapped.
    CHECK(mdrender::document_title("---\ntitle: \"Quoted\"\n---\n") ==
          "Quoted");
    CHECK(mdrender::document_title("---\ntitle: 'Single'\n---\n") == "Single");
    // A block with no title falls through to the heading rather than giving
    // up -- the TechNote template's front matter has no title: key.
    CHECK(mdrender::document_title("---\nauthor: B. Graham\n---\n\n# Fell "
                                   "Through\n") == "Fell Through");
    // An empty title: is not a title.
    CHECK(mdrender::document_title("---\ntitle:   \n---\n\n# Heading\n") ==
          "Heading");
}

TEST_CASE("a heading inside a code fence is not the title",
          "[mdrender][title]")
{
    // The reason this goes through extract_outline rather than scanning for
    // '#': a document opening with a shell transcript would otherwise be
    // titled by its first comment.
    const std::string doc =
        "```sh\n# not a heading\n```\n\n# Real Heading\n";
    CHECK(mdrender::document_title(doc) == "Real Heading");
}
